# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Myhr Studio
email: myhr.studio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Game Development Redefined
baseurl: "/webpage" # the subpath of your site, e.g. /blog
url: "https://myhrstudio.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: myhrstudio
#github_username:  rassolkro
facebook_username: myhrstudio
instagram_username: myhrstudio
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: 67 Keri ave.
address_city: Yerevan
address_state: Armenia #State for Country
address_zip: 0001

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
destination: _site/blog
paginate: 2
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate, jekyll-feed]